import { Button } from '@/components/ui/button';
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card';
import { Loader2, RefreshCw, Sparkles } from 'lucide-react';
import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { csrfHeaders } from '@/lib/ai';
import { humanizeAiError, MARKDOWN_COMPONENTS } from './ai-shared';

interface AnalysisResponse {
    ok: boolean;
    analysis?: string;
    message?: string;
    generated_at?: string;
}

/**
 * On-demand executive summary of the whole project portfolio,
 * generated by the shared AiService through /analytics/ai-analysis.
 */
export function AIInsights() {
    const [analysis, setAnalysis] = useState<string | null>(null);
    const [generatedAt, setGeneratedAt] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const generateAnalysis = async () => {
        setLoading(true);
        setError(null);
        try {
            const response = await fetch('/analytics/ai-analysis', {
                method: 'POST',
                credentials: 'same-origin',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest',
                    Accept: 'application/json',
                    ...csrfHeaders(),
                },
            });

            const data = (await response.json()) as AnalysisResponse;
            if (!response.ok || !data.ok) {
                throw new Error(data.message || 'AI gagal menghasilkan analisis.');
            }

            setAnalysis(data.analysis ?? null);
            setGeneratedAt(data.generated_at ?? null);
        } catch (err) {
            setError(humanizeAiError((err as Error)?.message));
        } finally {
            setLoading(false);
        }
    };

    return (
        <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-4">
                <div className="space-y-1">
                    <CardTitle className="flex items-center gap-2 text-base">
                        <Sparkles className="h-4 w-4 text-primary" />
                        AI Project Insights
                    </CardTitle>
                    <CardDescription>
                        {generatedAt
                            ? `Diperbarui ${new Date(generatedAt).toLocaleString('id-ID')}`
                            : 'Powered by DeepSeek AI'}
                    </CardDescription>
                </div>
                <Button
                    variant="outline"
                    size="sm"
                    onClick={generateAnalysis}
                    disabled={loading}
                    className="h-8 shadow-sm"
                >
                    {loading ? (
                        <>
                            <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" />
                            Menganalisis...
                        </>
                    ) : (
                        <>
                            <RefreshCw className="mr-2 h-3.5 w-3.5" />
                            {analysis ? 'Generate Ulang' : 'Generate Analisis'}
                        </>
                    )}
                </Button>
            </CardHeader>

            {!analysis && !error && !loading && (
                <CardContent className="py-10 text-center text-muted-foreground">
                    <div className="flex flex-col items-center justify-center gap-2">
                        <Sparkles className="h-8 w-8 text-muted-foreground/30" />
                        <p className="text-sm">
                            Klik tombol di atas untuk menganalisis data proyek.
                        </p>
                    </div>
                </CardContent>
            )}

            {(analysis || error) && (
                <CardContent>
                    {error ? (
                        <div className="rounded-md border border-destructive/20 bg-destructive/10 p-4 text-sm text-destructive">
                            {error}
                        </div>
                    ) : (
                        <div className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground">
                            <ReactMarkdown
                                remarkPlugins={[remarkGfm]}
                                components={MARKDOWN_COMPONENTS}
                            >
                                {analysis || ''}
                            </ReactMarkdown>
                        </div>
                    )}
                </CardContent>
            )}
        </Card>
    );
}
