import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useBreadcrumbs } from '@/hooks/use-breadcrumbs';
import AppLayout from '@/layouts/app-layout';
import { Head, useForm } from '@inertiajs/react';
import { Plus } from 'lucide-react';
import { type ReactElement } from 'react';
import { useTranslation } from 'react-i18next';
interface Schedule { id: number; equipment: { code: string; name: string }; interval_days: number|null; interval_runtime_minutes: number|null; next_due_at: string|null; is_active: boolean; }
function SchedulesPage({ schedules, equipment }: { schedules: Schedule[]; equipment: { id: number; code: string; name: string }[] }) { const { t } = useTranslation('maintenance'); const form = useForm({ equipment_id: '', interval_days: '', interval_runtime_minutes: '', next_due_at: '', is_active: true }); useBreadcrumbs([{ title: t('schedule.title'), href: '/maintenance/schedules' }]); const submit = (e: React.FormEvent) => { e.preventDefault(); form.post('/maintenance/schedules', { preserveScroll: true, onSuccess: () => form.reset() }); }; return <><Head title={t('schedule.title')} /><div className="space-y-6 p-4 md:p-6"><h1 className="font-display text-2xl font-semibold tracking-tight">{t('schedule.title')}</h1><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Plus className="size-4" />{t('schedule.add')}</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><Label>{t('schedule.equipment')}</Label><select className="h-9 w-full border bg-background px-3 text-sm" value={form.data.equipment_id} onChange={e => form.setData('equipment_id', e.target.value)} required><option value="">-</option>{equipment.map(item => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></div><div><Label>{t('schedule.interval_days')}</Label><Input type="number" min="1" value={form.data.interval_days} onChange={e => form.setData('interval_days', e.target.value)} /></div><div><Label>{t('schedule.next_due')}</Label><Input type="datetime-local" value={form.data.next_due_at} onChange={e => form.setData('next_due_at', e.target.value)} required /></div><div className="flex items-end"><Button variant="save"><Plus />{t('common.save')}</Button></div></form></CardContent></Card><Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-muted-foreground"><th className="px-4 py-3">{t('schedule.equipment')}</th><th className="px-4 py-3">{t('schedule.interval_days')}</th><th className="px-4 py-3">{t('schedule.next_due')}</th><th className="px-4 py-3">{t('schedule.active')}</th></tr></thead><tbody>{schedules.length === 0 ? <tr><td colSpan={4} className="px-4 py-10 text-center text-muted-foreground">{t('schedule.empty')}</td></tr> : schedules.map(item => <tr key={item.id} className="border-b last:border-0"><td className="px-4 py-3 font-medium">{item.equipment.code} · {item.equipment.name}</td><td className="px-4 py-3">{item.interval_days ?? '-'}</td><td className="px-4 py-3">{item.next_due_at ? new Date(item.next_due_at).toLocaleString() : '-'}</td><td className="px-4 py-3">{item.is_active ? t('schedule.active') : '-'}</td></tr>)}</tbody></table></CardContent></Card></div></>; }
SchedulesPage.layout = (page: ReactElement) => <AppLayout>{page}</AppLayout>;
export default SchedulesPage;
